### ISSUE TITLE
Error: The node API for `babel` has been moved to `babel-core`.

### ISSUE THREAD

**Issue by jmcmullen** [researchgate/gemini-babel#3]
```
▶ gemini update                  
Critical error:
Error: The node API for `babel` has been moved to `babel-core`.
    at Object.<anonymous> (/usr/local/lib/node_modules/babel/index.js:1:69)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.require (/usr/local/lib/node_modules/gemini/node_modules/plugins-loader/lib/utils.js:4:29)
    at module.exports.e (/usr/local/lib/node_modules/gemini/node_modules/plugins-loader/lib/require-plugin.js:21:26)
    at /usr/local/lib/node_modules/gemini/node_modules/plugins-loader/lib/loader.js:19:40
    at Loader.create.load.forEach (/usr/local/lib/node_modules/gemini/node_modules/plugins-loader/lib/index.js:9:30)
    at Array.forEach (native)
    at Object.exports.load (/usr/local/lib/node_modules/gemini/node_modules/plugins-loader/lib/index.js:9:10)
    at Gemini._loadPlugins (/usr/local/lib/node_modules/gemini/lib/gemini.js:112:23)
    at new Gemini (/usr/local/lib/node_modules/gemini/lib/gemini.js:46:14)
    at Promise.try (/usr/local/lib/node_modules/gemini/lib/cli/index.js:101:24)
    at tryCatcher (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/gemini/node_modules/bluebird/js/release/method.js:39:29)
    at runGemini (/usr/local/lib/node_modules/gemini/lib/cli/index.js:98:23)
    at Command.program.command.allowUnknownOption.option.option.description.action (/usr/local/lib/node_modules/gemini/lib/cli/index.js:29:37)
    at Command.listener (/usr/local/lib/node_modules/gemini/node_modules/commander/index.js:301:8)
```
Config:
```
system:{
        plugins: {
            babel:  {
                presets: ['babel-preset-koa2-node7']
            }
        }
    }
```
Any suggestions on how to fix this?

**Comment by SevInf** [comment]
Hi. It looks the gemini tries to load incorrect package. Can you try using this config:

```
system:{
        plugins: {
            'gemini-babel':  {
                presets: ['babel-preset-koa2-node7']
            }
        }
    }
```

**Comment by jmcmullen** [comment]
Perfect! Thanks mate.
